name: TAMUHack-2020
channels:
- conda-forge
dependencies:
- python=3.7
- PyAudio
- portaudio
- pillow
- fastapi
- requests
- pip
- pip:
  - google-cloud-speech
  - google-cloud-vision
  - google-cloud
  - uvicorn
  - pymongo
