name: TAMUHack-2020
channels:
- conda-forge
dependencies:
- fastapi
- pillow
- pip
- portaudio
- requests
- PyAudio
- opencv
- python=3.7
- pip:
  - google-cloud-speech
  - google-cloud-vision
  - google-cloud
  - uvicorn
  - pymongo
